# Generated by Django 5.1.6 on 2025-02-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destino",
            fields=[
                ("iden", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("explicacion", models.TextField()),
                ("imagen", models.ImageField(upload_to="inicio")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "destino",
                "verbose_name_plural": "destinos",
            },
        ),
    ]
