# Generated by Django 5.1.6 on 2025-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destino",
            name="imagen",
            field=models.ImageField(upload_to="destinos"),
        ),
    ]
